# Generated by Django 5.1.4 on 2024-12-18 01:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedulemyapp', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=100, verbose_name='参加登録'),
        ),
        migrations.AlterField(
            model_name='log',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log', to='schedulemyapp.movie', verbose_name='イベント登録'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie', to='schedulemyapp.director', verbose_name='参加登録'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100, verbose_name='イベント登録'),
        ),
    ]
