# Generated by Django 5.1.4 on 2024-12-18 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='イベント登録')),
                ('description', models.TextField(blank=True, verbose_name='詳細')),
            ],
        ),
    ]
