# Generated by Django 5.1.4 on 2024-12-18 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sche', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sche',
            name='date',
            field=models.TextField(blank=True, verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='sche',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='sche',
            name='title',
            field=models.CharField(max_length=200, verbose_name='イベント登録'),
        ),
    ]
