# Generated by Django 5.1.4 on 2024-12-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sche', '0002_sche_date_alter_sche_description_alter_sche_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sche',
            name='date',
            field=models.TextField(verbose_name='詳細'),
        ),
        migrations.AlterField(
            model_name='sche',
            name='description',
            field=models.TextField(verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='sche',
            name='title',
            field=models.CharField(max_length=200, verbose_name='イベント名'),
        ),
    ]
