# Generated by Django 5.1.1 on 2025-02-02 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suntory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='choice',
            field=models.CharField(blank=True, choices=[('option1', 'オプション1'), ('option2', 'オプション2'), ('option3', 'オプション3')], max_length=50, null=True),
        ),
    ]
