# Generated by Django 5.1.1 on 2025-02-02 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suntory', '0002_main_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='choice',
        ),
        migrations.AddField(
            model_name='main',
            name='option1_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main',
            name='option2_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='main',
            name='option3_count',
            field=models.IntegerField(default=0),
        ),
    ]
