# Generated by Django 5.1.1 on 2025-02-02 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('suntory', '0003_remove_main_choice_main_option1_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='option1_count',
        ),
        migrations.RemoveField(
            model_name='main',
            name='option2_count',
        ),
        migrations.RemoveField(
            model_name='main',
            name='option3_count',
        ),
    ]
